# Generated by Django 5.1.2 on 2025-01-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="barcode",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="item",
            name="cost",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="item",
            name="department",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
