# Generated by Django 5.1.2 on 2025-01-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos_app", "0002_alter_item_barcode_alter_item_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="barcode",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
